ACCESS_TOKEN_EXPIRE_MINUTES = 30
ALGORITHM = "HS256"
REFRESH_SECRET_KEY = "your_refresh_secret_key" # Change this!
REFRESH_TOKEN_EXPIRE_DAYS = 7
ACCESS_SECRET_KEY = "your_secret_key"  # Change this!
ACCESS_TOKEN_TYPE = "ACCESS"
REFRESH_TOKEN_TYPE = "REFRESH"